import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, BookOpen, CalendarRange, CheckCircle2, Database, ExternalLink, FileText, Scale } from 'lucide-react';
import { notFound } from 'next/navigation';
import { getCurrentUser } from '../../../lib/auth';
import { getJurisdictionId } from '../../../lib/jurisdiction';
import { prisma } from '../../../lib/prisma';
import { SiteNav } from '../../components/SiteNav';
import { BriefingPrintButton } from './BriefingPrintButton';

export const dynamic = 'force-dynamic';

export default async function BriefingDetailPage({ params, searchParams }) {
  const [{ slug }, query, user] = await Promise.all([params, searchParams, getCurrentUser()]);
  const briefing = await prisma.briefing.findFirst({
    where: { jurisdictionId: getJurisdictionId(), slug, reviewStatus: 'PUBLISHED' },
    select: {
      slug: true,
      title: true,
      briefingType: true,
      targetTheme: true,
      dateRangeStart: true,
      dateRangeEnd: true,
      testimonyCount: true,
      executiveSummary: true,
      keyFindings: true,
      patternAnalysis: true,
      silenceGaps: true,
      recommendations: true,
      claimVsExperience: true,
      generatedBy: true,
      reviewedAt: true,
      reviewStatus: true,
      publishedAt: true,
      partnerReviewOverrideReason: true,
      partnerReviewOverriddenAt: true,
      partnerReviewOverriddenBy: { select: { name: true } },
      partnerReviews: {
        orderBy: { deadline: 'asc' },
        select: {
          status: true,
          deadline: true,
          reviewedAt: true,
          organization: { select: { name: true } },
          reviewedBy: { select: { name: true } },
        },
      },
      targetAlgorithm: {
        select: {
          slug: true,
          name: true,
          useCase: true,
          agencyName: true,
          location: true,
          impactLevel: true,
        },
      },
      reviewedBy: { select: { name: true } },
      generationJobs: {
        where: { status: 'COMPLETED' },
        orderBy: { completedAt: 'desc' },
        take: 1,
        select: { completedAt: true, useClaude: true },
      },
    },
  });
  if (!briefing) notFound();

  const findings = arrayValue(briefing.keyFindings);
  const recommendations = arrayValue(briefing.recommendations);
  const claimRows = arrayValue(briefing.claimVsExperience);
  const silenceRows = arrayValue(briefing.silenceGaps);
  const lens = ['community', 'intermediary', 'government'].includes(query?.lens) ? query.lens : 'community';
  const explorerParams = new URLSearchParams({
    lens,
    scope: briefing.targetAlgorithm ? 'algorithm' : 'overview',
    reading: ['plain', 'standard', 'detailed'].includes(query?.reading) ? query.reading : 'detailed',
    language: typeof query?.language === 'string' ? query.language : 'en',
  });
  if (briefing.targetAlgorithm) explorerParams.set('algorithm', briefing.targetAlgorithm.slug);
  const latestGeneration = briefing.generationJobs[0];
  const evidenceWindow = dateRange(briefing.dateRangeStart, briefing.dateRangeEnd);
  const partnerReview = partnerReviewLabel(briefing);
  const pdfBriefing = {
    slug: briefing.slug,
    title: briefing.title,
    type: typeLabel(briefing.briefingType),
    subject: briefing.targetAlgorithm?.name || briefing.targetTheme || 'Cross-cutting corpus',
    executiveSummary: briefing.executiveSummary || 'No executive summary was provided.',
    metadata: [
      { label: 'Approved stories', value: String(briefing.testimonyCount ?? 0) },
      { label: 'Evidence window', value: evidenceWindow },
      { label: 'Review status', value: statusLabel(briefing.reviewStatus) },
      { label: 'Reviewed by', value: briefing.reviewedBy?.name || 'Editorial reviewer' },
      { label: 'Published', value: formatDate(briefing.publishedAt) },
      { label: 'Generated by', value: generatorLabel(briefing.generatedBy, latestGeneration) },
    ],
    patternAnalysis: briefing.patternAnalysis || '',
    keyFindings: findings.map(textValue).filter(Boolean),
    recommendations: recommendations.map(textValue).filter(Boolean),
    claimGroups: claimRows.map((row, index) => ({
      name: row?.algorithmName || `Evidence group ${index + 1}`,
      experienceCount: Number(row?.experienceCount || 0),
      matchMethod: row?.matchMethod || 'Briefing evidence match',
      claims: arrayValue(row?.claims).map((claim) => ({
        text: textValue(claim),
        source: typeof claim === 'object' && claim ? claim.source || '' : '',
      })).filter(({ text }) => text),
      examples: arrayValue(row?.experienceExamples).slice(0, 2).map((example) => ({
        title: example?.title || textValue(example),
        impact: example?.impact ? statusLabel(example.impact) : '',
      })).filter(({ title }) => title),
    })),
    silenceRows: silenceRows.map((row, index) => ({
      system: row?.algorithmName || `System ${index + 1}`,
      priority: statusLabel(row?.priority || 'Review'),
      volume: `${row?.approvedTestimonyCount ?? '-'} / ${row?.expectedVolume ?? '-'}`,
      score: Number.isFinite(Number(row?.silenceScore)) ? Number(row.silenceScore).toFixed(2) : '-',
    })),
    provenance: [
      {
        label: 'Review',
        value: `${statusLabel(briefing.reviewStatus)}${briefing.reviewedBy?.name ? ` by ${briefing.reviewedBy.name}` : ''}${briefing.reviewedAt ? ` on ${formatDate(briefing.reviewedAt)}` : ''}.`,
      },
      { label: 'Partner review', value: partnerReview },
      {
        label: 'Publication',
        value: `Published ${formatDate(briefing.publishedAt)} from a snapshot of ${briefing.testimonyCount ?? 0} approved stories.`,
      },
      {
        label: 'Generation',
        value: `${generatorLabel(briefing.generatedBy, latestGeneration)}. Narrative and computed groupings remain traceable to this briefing record.`,
      },
      {
        label: 'Evidence boundary',
        value: `Evidence covers ${evidenceWindow}. Counts may differ from the live explorer after new stories are approved.`,
      },
    ],
  };

  return (
    <main className="min-h-screen bg-[#ede8dd] text-slate-950">
      <SiteNav currentUser={user} />

      <div className="border-b border-slate-700 bg-[#171a1f] text-white">
        <div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6">
          <Link href="/briefings" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-slate-200 hover:text-amber-300">
            <ArrowLeft className="h-4 w-4" aria-hidden="true" />
            All briefings
          </Link>
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
            <BriefingPrintButton briefing={pdfBriefing} />
          </div>
        </div>
      </div>

      <article className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
        <header className="relative overflow-hidden rounded-t-2xl bg-[#171a1f] px-6 py-10 text-white sm:px-10 sm:py-14">
          <div className="absolute inset-y-0 right-0 w-1/3 bg-[radial-gradient(circle_at_center,rgba(252,211,77,.25),transparent_67%)]" />
          <div className="relative max-w-4xl">
            <div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-[0.16em]">
              <span className="rounded-full border border-amber-300/50 bg-amber-300/10 px-3 py-1 text-amber-200">{typeLabel(briefing.briefingType)}</span>
              <span className="text-slate-300">{briefing.targetAlgorithm?.name || briefing.targetTheme || 'Cross-cutting corpus'}</span>
            </div>
            <h1 className="mt-6 max-w-4xl font-serif text-4xl leading-tight sm:text-6xl">{briefing.title}</h1>
            <p className="mt-6 max-w-3xl text-base leading-7 text-slate-200 sm:text-lg">
              {briefing.executiveSummary || 'No executive summary was provided.'}
            </p>
          </div>
        </header>

        <div className="grid border-x border-b border-slate-300 bg-[#fffdf8] lg:grid-cols-[260px_minmax(0,1fr)]">
          <aside className="border-b border-slate-300 bg-[#f4efe4] p-6 lg:border-b-0 lg:border-r lg:p-8">
            <p className="font-mono text-xs font-bold uppercase tracking-[0.16em] text-amber-800">Evidence record</p>
            <dl className="mt-5 grid grid-cols-2 gap-x-4 gap-y-5 text-sm lg:grid-cols-1">
              <Metadata icon={BookOpen} label="Approved stories" value={String(briefing.testimonyCount ?? 0)} />
                <Metadata icon={CalendarRange} label="Evidence window" value={evidenceWindow} />
              <Metadata icon={CheckCircle2} label="Review status" value={statusLabel(briefing.reviewStatus)} />
              <Metadata icon={Scale} label="Reviewed by" value={briefing.reviewedBy?.name || 'Editorial reviewer'} />
              <Metadata icon={FileText} label="Published" value={formatDate(briefing.publishedAt)} />
              <Metadata icon={Database} label="Generated by" value={generatorLabel(briefing.generatedBy, latestGeneration)} />
            </dl>

            {briefing.targetAlgorithm ? (
              <div className="mt-7 border-t border-slate-300 pt-6">
                <p className="text-xs font-bold uppercase tracking-wide text-slate-500">System record</p>
                <Link href={`/algorithms/${briefing.targetAlgorithm.slug}`} className="mt-2 inline-flex items-start gap-2 text-sm font-bold text-amber-900 hover:underline">
                  {briefing.targetAlgorithm.name}
                  <ArrowUpRight className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
                </Link>
                <p className="mt-1 text-xs leading-5 text-slate-600">{briefing.targetAlgorithm.agencyName || 'Agency not listed'} · {briefing.targetAlgorithm.useCase}</p>
              </div>
            ) : null}

            <Link
              href={`/briefings/explore?${explorerParams.toString()}`}
              className="mt-7 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-md border border-amber-800 px-3 text-sm font-bold text-amber-900 hover:bg-amber-100"
            >
              Open interactive evidence
              <ExternalLink className="h-4 w-4" aria-hidden="true" />
            </Link>
          </aside>

          <div className="min-w-0 p-6 sm:p-10">
            {briefing.patternAnalysis ? (
              <section className="border-l-4 border-amber-400 bg-amber-50 px-5 py-4">
                <h2 className="font-serif text-2xl">How to read this briefing</h2>
                <p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-700">{briefing.patternAnalysis}</p>
              </section>
            ) : null}

            <TextList title="Key findings" items={findings} />
            <TextList title="Recommendations" items={recommendations} ordered />
            <ClaimEvidence rows={claimRows} />
            <SilenceEvidence rows={silenceRows} />

            <section className="mt-10 border-t border-slate-300 pt-7" aria-labelledby="provenance-heading">
              <h2 id="provenance-heading" className="font-serif text-2xl">Review and provenance</h2>
              <div className="mt-4 grid gap-4 text-sm sm:grid-cols-2">
                <ProvenanceCard label="Review" value={`${statusLabel(briefing.reviewStatus)}${briefing.reviewedBy?.name ? ` by ${briefing.reviewedBy.name}` : ''}${briefing.reviewedAt ? ` on ${formatDate(briefing.reviewedAt)}` : ''}.`} />
                <ProvenanceCard label="Partner review" value={partnerReview} />
                <ProvenanceCard label="Publication" value={`Published ${formatDate(briefing.publishedAt)} from a snapshot of ${briefing.testimonyCount ?? 0} approved stories.`} />
                <ProvenanceCard label="Generation" value={`${generatorLabel(briefing.generatedBy, latestGeneration)}. Narrative and computed groupings remain traceable to this briefing record.`} />
                <ProvenanceCard label="Evidence boundary" value={`Evidence covers ${evidenceWindow}. Counts may differ from the live explorer after new stories are approved.`} />
              </div>
            </section>
          </div>
        </div>

        <footer className="rounded-b-2xl border-x border-b border-slate-300 bg-white px-6 py-4 text-xs text-slate-500 sm:px-10">
          AlgoStories briefing · {briefing.slug} · Reviewed public record.
        </footer>
      </article>
    </main>
  );
}

function Metadata({ icon: Icon, label, value }) {
  return (
    <div>
      <dt className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-500">
        <Icon className="h-3.5 w-3.5 text-amber-800" aria-hidden="true" />
        {label}
      </dt>
      <dd className="mt-1 leading-5 text-slate-900">{value}</dd>
    </div>
  );
}

function TextList({ title, items, ordered = false }) {
  if (!items.length) return null;
  const List = ordered ? 'ol' : 'ul';
  return (
    <section className="mt-10">
      <h2 className="font-serif text-3xl">{title}</h2>
      <List className="mt-5 grid gap-3">
        {items.map((item, index) => (
          <li key={`${title}-${index}`} className="grid grid-cols-[2rem_1fr] gap-3 border-t border-slate-200 pt-3 text-sm leading-7 text-slate-700">
            <span className="font-mono text-xs font-bold text-amber-800">{String(index + 1).padStart(2, '0')}</span>
            <span>{textValue(item)}</span>
          </li>
        ))}
      </List>
    </section>
  );
}

function ClaimEvidence({ rows }) {
  if (!rows.length) return null;
  return (
    <section className="mt-10" aria-labelledby="claims-heading">
      <div className="flex flex-wrap items-end justify-between gap-2">
        <h2 id="claims-heading" className="font-serif text-3xl">Claims and reported experience</h2>
        <span className="text-xs font-bold uppercase tracking-wide text-slate-500">Descriptive, not adjudicated</span>
      </div>
      <div className="mt-5 grid gap-4">
        {rows.map((row, index) => {
          const claims = arrayValue(row?.claims);
          const examples = arrayValue(row?.experienceExamples);
          return (
            <article key={row?.algorithmSlug || index} className="rounded-lg border border-slate-300 bg-white p-5">
              <h3 className="font-bold">{row?.algorithmName || `Evidence group ${index + 1}`}</h3>
              <p className="mt-1 text-xs text-slate-500">{Number(row?.experienceCount || 0)} related experience records · {row?.matchMethod || 'Briefing evidence match'}</p>
              {claims.length ? (
                <div className="mt-4">
                  <p className="text-xs font-bold uppercase tracking-wide text-slate-500">Documented claims</p>
                  <ul className="mt-2 space-y-2 text-sm leading-6 text-slate-700">
                    {claims.map((claim, claimIndex) => <li key={claimIndex}>“{textValue(claim)}”{claim?.source ? <span className="text-slate-500"> — {claim.source}</span> : null}</li>)}
                  </ul>
                </div>
              ) : null}
              {examples.length ? (
                <div className="mt-4">
                  <p className="text-xs font-bold uppercase tracking-wide text-slate-500">Experience examples</p>
                  <ul className="mt-2 grid gap-2 text-sm sm:grid-cols-2">
                    {examples.map((example, exampleIndex) => (
                      <li key={example?.id || exampleIndex} className="rounded-md bg-slate-50 p-3">
                        <span className="font-semibold">{example?.title || textValue(example)}</span>
                        {example?.impact ? <span className="mt-1 block text-xs text-slate-500">Reported impact: {statusLabel(example.impact)}</span> : null}
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}
            </article>
          );
        })}
      </div>
    </section>
  );
}

function SilenceEvidence({ rows }) {
  if (!rows.length) return null;
  return (
    <section className="mt-10" aria-labelledby="silence-heading">
      <h2 id="silence-heading" className="font-serif text-3xl">Coverage and silence checks</h2>
      <p className="mt-2 text-sm leading-6 text-slate-600">Low story volume is a prompt for outreach, not evidence that no harm occurred.</p>
      <div className="mt-5 overflow-x-auto rounded-lg border border-slate-300">
        <table className="w-full min-w-[560px] border-collapse text-left text-sm">
          <thead className="bg-slate-100 text-xs uppercase tracking-wide text-slate-600">
            <tr>
              <th className="px-4 py-3">System</th>
              <th className="px-4 py-3">Priority</th>
              <th className="px-4 py-3">Approved / expected</th>
              <th className="px-4 py-3">Silence score</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row, index) => (
              <tr key={row?.algorithmSlug || index} className="border-t border-slate-200">
                <td className="px-4 py-3 font-semibold">{row?.algorithmName || `System ${index + 1}`}</td>
                <td className="px-4 py-3">{statusLabel(row?.priority || 'Review')}</td>
                <td className="px-4 py-3">{row?.approvedTestimonyCount ?? '—'} / {row?.expectedVolume ?? '—'}</td>
                <td className="px-4 py-3">{Number.isFinite(Number(row?.silenceScore)) ? Number(row.silenceScore).toFixed(2) : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function ProvenanceCard({ label, value }) {
  return (
    <div className="rounded-lg border border-slate-300 bg-slate-50 p-4">
      <h3 className="text-xs font-bold uppercase tracking-wide text-amber-800">{label}</h3>
      <p className="mt-2 leading-6 text-slate-700">{value}</p>
    </div>
  );
}

function arrayValue(value) {
  return Array.isArray(value) ? value : [];
}

function textValue(value) {
  if (typeof value === 'string') return value;
  if (!value || typeof value !== 'object') return '';
  return value.text || value.finding || value.summary || value.title || value.description || 'Evidence item';
}

function typeLabel(value) {
  return {
    ALGORITHM_SPECIFIC: 'Algorithm-specific briefing',
    THEMATIC: 'Thematic briefing',
    SILENCE_REPORT: 'Silence report',
    CROSS_CUTTING: 'Cross-cutting briefing',
  }[value] || 'Briefing';
}

function generatorLabel(value, generationJob) {
  if (generationJob?.useClaude) return 'Staff-requested assisted draft';
  return {
    staff_draft: 'Staff-generated evidence draft',
    seed: 'Seeded test briefing',
  }[value] || (value ? value.replaceAll('_', ' ') : 'Generation source recorded');
}

function partnerReviewLabel(briefing) {
  if (briefing.partnerReviewOverriddenAt) {
    const reviewer = briefing.partnerReviewOverriddenBy?.name || 'an administrator';
    return `Publication override recorded by ${reviewer} on ${formatDate(briefing.partnerReviewOverriddenAt)}: ${briefing.partnerReviewOverrideReason || 'No reason recorded.'}`;
  }
  if (!briefing.partnerReviews.length) return 'No partner organization was assigned to this legacy publication.';
  const approved = briefing.partnerReviews.filter(({ status }) => status === 'APPROVED');
  const organizations = approved.map(({ organization }) => organization.name).join(', ');
  return `${approved.length} of ${briefing.partnerReviews.length} assigned organizations approved${organizations ? `: ${organizations}` : ''}.`;
}

function statusLabel(value) {
  if (!value) return 'Not recorded';
  return String(value).replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function dateRange(start, end) {
  if (!start && !end) return 'All approved records at publication';
  if (start && end) return `${formatDate(start)} – ${formatDate(end)}`;
  return start ? `From ${formatDate(start)}` : `Through ${formatDate(end)}`;
}

function formatDate(value) {
  if (!value) return 'Not dated';
  return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeZone: 'UTC' }).format(value);
}
