export const algorithmsData = [
  {
    "id": "6988af2bebff0fdc4b5bdbaf",
    "name": "Fraud Detection System",
    "description": "Machine learning algorithm that analyzes transaction patterns to identify potentially fraudulent activities in government benefit programs.",
    "category": "Risk Assessment",
    "organization": "Department of Social Services",
    "status": "Active",
    "use_case": "Fraud Detection",
    "use_case_brief": "Detects and prevents fraudulent activities in public benefit programs by analyzing patterns and flagging suspicious claims",
    "impact_level": "High",
    "documentation_url": "https://example.gov/fraud-detection-docs",
    "current_version": "3.2.1",
    "data_used": "Transaction history, claim patterns, cross-referenced databases, applicant demographics",
    "decision_type": "Risk scoring and flagging for manual review",
    "purpose": "To detect and prevent fraudulent claims in social welfare programs by analyzing transaction patterns and claimant behavior",
    "storyboard_images": ["/Picture1.png"],
    "used_by": "State Benefits Administration Office",
    "location": "Pittsburgh",
    "year_deployed": 2020,
    "year_introduced": 2019,
    "views": 0,
    "created_date": "2026-02-08T15:43:39.504000"
  },
  {
    "id": "6988af2bebff0fdc4b5bdbb0",
    "name": "Traffic Flow Optimizer",
    "description": "AI-powered system that manages traffic signal timing based on real-time traffic data to reduce congestion and improve commute times.",
    "category": "Decision Making",
    "organization": "City Transportation Authority",
    "status": "Active",
    "use_case": "Traffic Management",
    "use_case_brief": "Optimizes traffic flow in urban areas by adjusting signal timing based on real-time vehicle data to reduce congestion",
    "impact_level": "Medium",
    "documentation_url": "https://example.gov/traffic-optimizer-docs",
    "current_version": "2.5.0",
    "data_used": "Traffic sensor data, vehicle counts, GPS data from public transit, historical traffic patterns",
    "decision_type": "Automated signal timing adjustments",
    "purpose": "To optimize traffic signal timing dynamically based on real-time vehicle flow and reduce urban congestion",
    "storyboard_images": ["/Picture1.png"],
    "used_by": "Municipal Traffic Control Center",
    "location": "Pittsburgh",
    "year_deployed": 2022,
    "year_introduced": 2021,
    "views": 0,
    "created_date": "2026-02-08T15:43:39.504000"
  },
  {
    "id": "6988af2bebff0fdc4b5bdbb1",
    "name": "Student Risk Assessment",
    "description": "Predictive model that identifies students at risk of dropping out based on attendance, grades, and engagement metrics.",
    "category": "Classification",
    "organization": "Ministry of Education",
    "status": "Under Review",
    "use_case": "Student Support",
    "use_case_brief": "Identifies students at risk of dropping out to enable early intervention and provide necessary support services",
    "impact_level": "High",
    "documentation_url": "https://example.gov/student-risk-docs",
    "current_version": "4.1.3",
    "data_used": "Attendance records, grade performance, behavioral incidents, socioeconomic indicators",
    "decision_type": "Risk level classification (low, medium, high)",
    "purpose": "To identify students at risk of dropping out early to enable timely intervention and support services",
    "storyboard_images": ["/Picture1.png"],
    "used_by": "Public School Districts",
    "location": "Pittsburgh",
    "year_deployed": 2019,
    "year_introduced": 2018,
    "views": 0,
    "created_date": "2026-02-08T15:43:39.504000"
  },
  {
    "id": "6988af2bebff0fdc4b5bdbb2",
    "name": "Job Matching Algorithm",
    "description": "Recommendation system that matches job seekers with suitable employment opportunities based on skills, experience, and preferences.",
    "category": "Recommendation",
    "organization": "Employment Services Agency",
    "status": "Active",
    "use_case": "Job Matching",
    "use_case_brief": "Connects job seekers with suitable employment opportunities by matching their skills and preferences with available positions",
    "impact_level": "Medium",
    "documentation_url": "https://example.gov/job-matching-docs",
    "current_version": "2.8.4",
    "data_used": "Resume data, skill assessments, job posting requirements, employment history",
    "decision_type": "Ranked job recommendations",
    "purpose": "To match unemployed individuals with suitable job openings based on their skills, experience, and career preferences",
    "storyboard_images": ["/Picture1.png"],
    "used_by": "National Employment Service Centers",
    "location": "Pittsburgh",
    "year_deployed": 2021,
    "year_introduced": 2020,
    "views": 0,
    "created_date": "2026-02-08T15:43:39.504000"
  },
  {
    "id": "6988af2bebff0fdc4b5bdbb3",
    "name": "Energy Consumption Predictor",
    "description": "Time-series forecasting model that predicts energy demand to optimize power grid management and reduce costs.",
    "category": "Machine Learning",
    "organization": "National Energy Board",
    "status": "Active",
    "use_case": "Energy Forecasting",
    "use_case_brief": "Predicts energy demand patterns to optimize power grid distribution and reduce costs while minimizing waste",
    "impact_level": "Low",
    "documentation_url": "https://example.gov/energy-predictor-docs",
    "current_version": "1.6.2",
    "data_used": "Historical consumption data, weather patterns, seasonal trends, industrial usage schedules",
    "decision_type": "Demand forecasting and resource allocation",
    "purpose": "To forecast energy demand and optimize power distribution across the grid to minimize waste and costs",
    "storyboard_images": ["/Picture1.png"],
    "used_by": "Regional Power Grid Operators",
    "location": "Pittsburgh",
    "year_deployed": 2023,
    "year_introduced": 2022,
    "views": 0,
    "created_date": "2026-02-08T15:43:39.504000"
  },
  {
    "id": "6988af2bebff0fdc4b5bdbb4",
    "name": "Allegheny Family Screening Tool",
    "description": "To help child welfare agencies prioritize investigations and manage significant volumes of calls by identifying which children are at higher risk.",
    "category": "Risk Assessment",
    "organization": "Allegheny County Department of Human Services",
    "status": "Active",
    "use_case": "Child Welfare",
    "use_case_brief": "Helps child welfare agencies prioritize investigations and manage call volumes by identifying which children are at higher risk of abuse or neglect",
    "impact_level": "High",
    "documentation_url": "https://example.gov/afst-docs",
    "current_version": "1.0",
    "data_used": "Family demographics, historical case data, and governmental data such as criminal, public health, or public benefits records",
    "decision_type": "Generates a risk score interpreted as the likelihood of abuse or neglect, shown to workers to inform their front-end screening decisions",
    "purpose": "To help child welfare agencies prioritize investigations and manage significant volumes of calls by identifying which children are at higher risk",
    "storyboard_images": ["/Picture1.png"],
    "used_by": "Hotline call screeners and child welfare supervisors",
    "location": "Allegheny County",
    "year_deployed": 2015,
    "year_introduced": 2015,
    "views": 0,
    "created_date": "2026-02-08T15:43:39.504000"
  },
  {
    "id": "6988af2bebff0fdc4b5bdbb5",
    "name": "Housing Allocation Algorithm",
    "description": "A tool designed to prioritize scarce housing resources by predicting an applicant's risk of adverse events (e.g., emergency room visits, mental health stays, or jail bookings) based on administrative data.",
    "category": "Risk Assessment",
    "organization": "Allegheny County Government",
    "status": "Active",
    "use_case": "Housing Prioritization",
    "use_case_brief": "Prioritizes scarce housing resources for individuals and families experiencing homelessness based on predicted risk of adverse events",
    "impact_level": "High",
    "documentation_url": "https://example.gov/housing-allocation-docs",
    "current_version": "1.0",
    "data_used": "Government administrative records, healthcare utilization data, Medicaid funding data, and criminal justice records",
    "decision_type": "Generates a risk score between 1 and 10 based on predicted likelihoods of adverse events, which staff use to assign applicants to specific housing waitlists",
    "purpose": "To prioritize scarce housing resources for individuals and families experiencing homelessness",
    "storyboard_images": ["/Picture1.png"],
    "used_by": "Allegheny County Government",
    "location": "Pittsburgh",
    "year_deployed": 2021,
    "year_introduced": 2018,
    "views": 0,
    "created_date": "2026-02-08T15:43:39.504000"
  }
];